package pi.pperformance.elite.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.Set; // For OneToMany relationship

@Entity
@Getter
@Setter
@NoArgsConstructor
@Table(name = "doctor_centre_examen") // Explicit table name for this subclass
public class DoctorCentreDexamen extends User implements Serializable {

    // id_DrCe from diagram is inherited as 'id' from User

    private String speciality; // Specific field for this type of user

    @Column(nullable = false) // Ensure it's not null
    private boolean isActive = false; // Add isActive field, default to false

    // Relationship: DoctorCentreDexamen 'rédiger' Document (1 to * - Owning Side)
    @OneToMany(mappedBy = "doctorCentreDexamen", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private Set<Document> documents;

    // Relationship: DoctorCentreDexamen 'orienter vers' CentreDexamen (0..1 to 1 - Owning Side)
    @ManyToOne
    @JoinColumn(name = "id_centre") // Foreign key column
    private CentreDexamen centreDexamen;

    // Constructor to set the role specifically for this entity
    public DoctorCentreDexamen(String firstName, String lastName, String email, String password, LocalDate birthDate, String tel, String address, String speciality, CentreDexamen centreDexamen) {
        super(firstName, lastName, email, password, birthDate, tel, address); // Call User constructor
        this.role = Role.DOCTOR_CENTRE_EXAMEN; // Set the role
        this.speciality = speciality;
        this.centreDexamen = centreDexamen;
        this.isActive = false; // Explicitly set to false on creation
        // Ensure createdAt and updatedAt are handled (already done in User constructor/PrePersist)
    }

    // Note: The default constructor is generated by Lombok's @NoArgsConstructor.
    // We might need to ensure the role is set correctly if that constructor is used.
    // Consider adding an @PostLoad or similar mechanism if needed, or rely on the parameterized constructor.

    // Note: The 'role' field itself is inherited from User. We just ensure it's set correctly via the constructor.
}
